spring:
  application:
    name: micrometer-observation
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${common.http.client.hc5.connect-timeout}
            read-timeout: ${common.http.client.hc5.socket-timeout}
          feignClient:
            url: http://127.0.0.1:8080/rest
        default-config:
      httpclient:
        hc5:
          enabled: true

common:
  http:
    client:
      hc5:
        connect-timeout: 3000
        socket-timeout: 5000
  rest:
    client:
      default:
        enabled: true
  context:
    service:
      default-inject-key-set:
        - test1
        - test2
      limit-set:
        - test1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com:
      github:
        ksewen:
          yorozuya:
            starter:
              aspect: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#debug: true
