spring:
  application:
    name: eureka-client
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${common.ok.http.client.connect-timeout}
            read-timeout: ${common.ok.http.client.read-timeout}
          #            logger-level: FULL
          restClient:
            url: http://127.0.0.1:8080/rest
      okhttp:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

common:
  ok:
    http:
      client:
        connect-timeout: 3000
        read-timeout: 5000
        write-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

#logging:
#  level:
#    okhttp3: debug
#debug: true
