spring:
  application:
    name: eureka-client
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${common.http.client.hc5.connect-timeout}
            read-timeout: ${common.http.client.hc5.socket-timeout}
          #            logger-level: FULL
      httpclient:
        hc5:
          enabled: true
    loadbalancer:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

common:
  http:
    client:
      hc5:
        connect-timeout: 3000
        socket-timeout: 5000
  rest:
    client:
      default:
        enabled: true
      loadbalancer:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

#debug: true
