spring:
  application:
    name: eureka-client
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${common.ok.http.client.connect-timeout}
            read-timeout: ${common.ok.http.client.read-timeout}
          #            logger-level: FULL
          restClient:
            url: http://127.0.0.1:38080/rest
      okhttp:
        enabled: true
        
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

common:
  ok:
    http:
      client:
        connect-timeout: 3000
        read-timeout: 5000
        write-timeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      restTemplateClient:
        minimumNumberOfCalls: 10
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

#logging:
#  level:
#    okhttp3: debug
debug: true
